name: Sync

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
          # 注意替换为你的 GitHub 源仓库地址
          src: "github/mxcall"
          # 注意替换为你的 Gitee 目标仓库地址
          dst: "gitee/mxcall"
          dst_key: "${{ secrets.GITEE_RSA_PRIVATE_KEY }}"
          dst_token: "${{ secrets.GITEE_TOKEN }}"
          static_list: "mxcall.github.io"
          clone_style: "https"
          force_update: true
          debug: true

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: mxcall
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: mxcall/mxcall